-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Interface exposing (..)


type CartDiscountAllocation
    = CartDiscountAllocation


type DiscountApplication
    = DiscountApplication


type DisplayableError
    = DisplayableError


type HasMetafields
    = HasMetafields


type Media
    = Media


type Node
    = Node


type OnlineStorePublishable
    = OnlineStorePublishable
