-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Shopify.Scalar exposing (defaultCodecs)


type alias DateTime =
    Shopify.Scalar.DateTime


type alias Decimal =
    Shopify.Scalar.Decimal


type alias Html =
    Shopify.Scalar.Html


type alias Id =
    Shopify.Scalar.Id


type alias Json =
    Shopify.Scalar.Json


type alias Money =
    Shopify.Scalar.Money


type alias Url =
    Shopify.Scalar.Url


codecs : Shopify.Scalar.Codecs DateTime Decimal Html Id Json Money Url
codecs =
    Shopify.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecDecimal = defaultCodecs.codecDecimal
        , codecHtml = defaultCodecs.codecHtml
        , codecId = defaultCodecs.codecId
        , codecJson = defaultCodecs.codecJson
        , codecMoney = defaultCodecs.codecMoney
        , codecUrl = defaultCodecs.codecUrl
        }
