-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Union exposing (..)


type Merchandise
    = Merchandise


type MetafieldParentResource
    = MetafieldParentResource


type MetafieldReference
    = MetafieldReference


type PricingValue
    = PricingValue


type SellingPlanCheckoutChargeValue
    = SellingPlanCheckoutChargeValue


type SellingPlanPriceAdjustmentValue
    = SellingPlanPriceAdjustmentValue
