-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CartEstimatedCost exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The estimated amount, before taxes and discounts, for the customer to pay at checkout. The checkout charge amount doesn't include any deferred payments that'll be paid at a later date. If the cart has no deferred payments, then the checkout charge amount is equivalent to`subtotal_amount`.
-}
checkoutChargeAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartEstimatedCost
checkoutChargeAmount object____ =
    Object.selectionForCompositeField "checkoutChargeAmount" [] object____ Basics.identity


{-| The estimated amount, before taxes and discounts, for the customer to pay.
-}
subtotalAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartEstimatedCost
subtotalAmount object____ =
    Object.selectionForCompositeField "subtotalAmount" [] object____ Basics.identity


{-| The estimated total amount for the customer to pay.
-}
totalAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartEstimatedCost
totalAmount object____ =
    Object.selectionForCompositeField "totalAmount" [] object____ Basics.identity


{-| The estimated duty amount for the customer to pay at checkout.
-}
totalDutyAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CartEstimatedCost
totalDutyAmount object____ =
    Object.selectionForCompositeField "totalDutyAmount" [] object____ (Basics.identity >> Decode.nullable)


{-| The estimated tax amount for the customer to pay at checkout.
-}
totalTaxAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CartEstimatedCost
totalTaxAmount object____ =
    Object.selectionForCompositeField "totalTaxAmount" [] object____ (Basics.identity >> Decode.nullable)
