-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CartCustomDiscountAllocation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The discounted amount that has been applied to the cart line.
-}
discountedAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartCustomDiscountAllocation
discountedAmount object____ =
    Object.selectionForCompositeField "discountedAmount" [] object____ Basics.identity


{-| The title of the allocated discount.
-}
title : SelectionSet String Shopify.Object.CartCustomDiscountAllocation
title =
    Object.selectionForField "String" "title" [] Decode.string
