-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CartLineCost exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The amount of the merchandise line.
-}
amountPerQuantity :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartLineCost
amountPerQuantity object____ =
    Object.selectionForCompositeField "amountPerQuantity" [] object____ Basics.identity


{-| The compare at amount of the merchandise line.
-}
compareAtAmountPerQuantity :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CartLineCost
compareAtAmountPerQuantity object____ =
    Object.selectionForCompositeField "compareAtAmountPerQuantity" [] object____ (Basics.identity >> Decode.nullable)


{-| The cost of the merchandise line before line-level discounts.
-}
subtotalAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartLineCost
subtotalAmount object____ =
    Object.selectionForCompositeField "subtotalAmount" [] object____ Basics.identity


{-| The total cost of the merchandise line.
-}
totalAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.CartLineCost
totalAmount object____ =
    Object.selectionForCompositeField "totalAmount" [] object____ Basics.identity
