-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CartLine exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


type alias AttributeRequiredArguments =
    { key : String }


{-| An attribute associated with the cart line.

  - key - The key of the attribute.

-}
attribute :
    AttributeRequiredArguments
    -> SelectionSet decodesTo Shopify.Object.Attribute
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CartLine
attribute requiredArgs____ object____ =
    Object.selectionForCompositeField "attribute" [ Argument.required "key" requiredArgs____.key Encode.string ] object____ (Basics.identity >> Decode.nullable)


{-| The attributes associated with the cart line. Attributes are represented as key-value pairs.
-}
attributes :
    SelectionSet decodesTo Shopify.Object.Attribute
    -> SelectionSet (List decodesTo) Shopify.Object.CartLine
attributes object____ =
    Object.selectionForCompositeField "attributes" [] object____ (Basics.identity >> Decode.list)


{-| The cost of the merchandise that the buyer will pay for at checkout. The costs are subject to change and changes will be reflected at checkout.
-}
cost :
    SelectionSet decodesTo Shopify.Object.CartLineCost
    -> SelectionSet decodesTo Shopify.Object.CartLine
cost object____ =
    Object.selectionForCompositeField "cost" [] object____ Basics.identity


{-| The discounts that have been applied to the cart line.
-}
discountAllocations :
    SelectionSet decodesTo Shopify.Interface.CartDiscountAllocation
    -> SelectionSet (List decodesTo) Shopify.Object.CartLine
discountAllocations object____ =
    Object.selectionForCompositeField "discountAllocations" [] object____ (Basics.identity >> Decode.list)


{-| The estimated cost of the merchandise that the buyer will pay for at checkout. The estimated costs are subject to change and changes will be reflected at checkout.
-}
estimatedCost :
    SelectionSet decodesTo Shopify.Object.CartLineEstimatedCost
    -> SelectionSet decodesTo Shopify.Object.CartLine
estimatedCost object____ =
    Object.selectionForCompositeField "estimatedCost" [] object____ Basics.identity


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.CartLine
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The merchandise that the buyer intends to purchase.
-}
merchandise :
    SelectionSet decodesTo Shopify.Union.Merchandise
    -> SelectionSet decodesTo Shopify.Object.CartLine
merchandise object____ =
    Object.selectionForCompositeField "merchandise" [] object____ Basics.identity


{-| The quantity of the merchandise that the customer intends to purchase.
-}
quantity : SelectionSet Int Shopify.Object.CartLine
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int


{-| The selling plan associated with the cart line and the effect that each selling plan has on variants when they're purchased.
-}
sellingPlanAllocation :
    SelectionSet decodesTo Shopify.Object.SellingPlanAllocation
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CartLine
sellingPlanAllocation object____ =
    Object.selectionForCompositeField "sellingPlanAllocation" [] object____ (Basics.identity >> Decode.nullable)
