-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CartDeliveryGroup exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


type alias CartLinesOptionalArguments =
    { first : OptionalArgument Int
    , after : OptionalArgument String
    , last : OptionalArgument Int
    , before : OptionalArgument String
    , reverse : OptionalArgument Bool
    }


{-| A list of cart lines for the delivery group.

  - first - Returns up to the first `n` elements from the list.
  - after - Returns the elements that come after the specified cursor.
  - last - Returns up to the last `n` elements from the list.
  - before - Returns the elements that come before the specified cursor.
  - reverse - Reverse the order of the underlying list.

-}
cartLines :
    (CartLinesOptionalArguments -> CartLinesOptionalArguments)
    -> SelectionSet decodesTo Shopify.Object.CartLineConnection
    -> SelectionSet decodesTo Shopify.Object.CartDeliveryGroup
cartLines fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { first = Absent, after = Absent, last = Absent, before = Absent, reverse = Absent }

        optionalArgs____ =
            [ Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "reverse" filledInOptionals____.reverse Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "cartLines" optionalArgs____ object____ Basics.identity


{-| The destination address for the delivery group.
-}
deliveryAddress :
    SelectionSet decodesTo Shopify.Object.MailingAddress
    -> SelectionSet decodesTo Shopify.Object.CartDeliveryGroup
deliveryAddress object____ =
    Object.selectionForCompositeField "deliveryAddress" [] object____ Basics.identity


{-| The delivery options available for the delivery group.
-}
deliveryOptions :
    SelectionSet decodesTo Shopify.Object.CartDeliveryOption
    -> SelectionSet (List decodesTo) Shopify.Object.CartDeliveryGroup
deliveryOptions object____ =
    Object.selectionForCompositeField "deliveryOptions" [] object____ (Basics.identity >> Decode.list)


{-| The ID for the delivery group.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.CartDeliveryGroup
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)
