-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CheckoutLineItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| Extra information in the form of an array of Key-Value pairs about the line item.
-}
customAttributes :
    SelectionSet decodesTo Shopify.Object.Attribute
    -> SelectionSet (List decodesTo) Shopify.Object.CheckoutLineItem
customAttributes object____ =
    Object.selectionForCompositeField "customAttributes" [] object____ (Basics.identity >> Decode.list)


{-| The discounts that have been allocated onto the checkout line item by discount applications.
-}
discountAllocations :
    SelectionSet decodesTo Shopify.Object.DiscountAllocation
    -> SelectionSet (List decodesTo) Shopify.Object.CheckoutLineItem
discountAllocations object____ =
    Object.selectionForCompositeField "discountAllocations" [] object____ (Basics.identity >> Decode.list)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.CheckoutLineItem
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The quantity of the line item.
-}
quantity : SelectionSet Int Shopify.Object.CheckoutLineItem
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int


{-| Title of the line item. Defaults to the product's title.
-}
title : SelectionSet String Shopify.Object.CheckoutLineItem
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| Unit price of the line item.
-}
unitPrice :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CheckoutLineItem
unitPrice object____ =
    Object.selectionForCompositeField "unitPrice" [] object____ (Basics.identity >> Decode.nullable)


{-| Product variant of the line item.
-}
variant :
    SelectionSet decodesTo Shopify.Object.ProductVariant
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CheckoutLineItem
variant object____ =
    Object.selectionForCompositeField "variant" [] object____ (Basics.identity >> Decode.nullable)
