-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CheckoutBuyerIdentity exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.CountryCode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The country code for the checkout. For example, `CA`.
-}
countryCode : SelectionSet (Maybe Shopify.Enum.CountryCode.CountryCode) Shopify.Object.CheckoutBuyerIdentity
countryCode =
    Object.selectionForField "(Maybe Enum.CountryCode.CountryCode)" "countryCode" [] (Shopify.Enum.CountryCode.decoder |> Decode.nullable)
