-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CreditCard exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The brand of the credit card.
-}
brand : SelectionSet (Maybe String) Shopify.Object.CreditCard
brand =
    Object.selectionForField "(Maybe String)" "brand" [] (Decode.string |> Decode.nullable)


{-| The expiry month of the credit card.
-}
expiryMonth : SelectionSet (Maybe Int) Shopify.Object.CreditCard
expiryMonth =
    Object.selectionForField "(Maybe Int)" "expiryMonth" [] (Decode.int |> Decode.nullable)


{-| The expiry year of the credit card.
-}
expiryYear : SelectionSet (Maybe Int) Shopify.Object.CreditCard
expiryYear =
    Object.selectionForField "(Maybe Int)" "expiryYear" [] (Decode.int |> Decode.nullable)


{-| The credit card's BIN number.
-}
firstDigits : SelectionSet (Maybe String) Shopify.Object.CreditCard
firstDigits =
    Object.selectionForField "(Maybe String)" "firstDigits" [] (Decode.string |> Decode.nullable)


{-| The first name of the card holder.
-}
firstName : SelectionSet (Maybe String) Shopify.Object.CreditCard
firstName =
    Object.selectionForField "(Maybe String)" "firstName" [] (Decode.string |> Decode.nullable)


{-| The last 4 digits of the credit card.
-}
lastDigits : SelectionSet (Maybe String) Shopify.Object.CreditCard
lastDigits =
    Object.selectionForField "(Maybe String)" "lastDigits" [] (Decode.string |> Decode.nullable)


{-| The last name of the card holder.
-}
lastName : SelectionSet (Maybe String) Shopify.Object.CreditCard
lastName =
    Object.selectionForField "(Maybe String)" "lastName" [] (Decode.string |> Decode.nullable)


{-| The masked credit card number with only the last 4 digits displayed.
-}
maskedNumber : SelectionSet (Maybe String) Shopify.Object.CreditCard
maskedNumber =
    Object.selectionForField "(Maybe String)" "maskedNumber" [] (Decode.string |> Decode.nullable)
