-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.CustomerResetByUrlPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The customer object which was reset.
-}
customer :
    SelectionSet decodesTo Shopify.Object.Customer
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CustomerResetByUrlPayload
customer object____ =
    Object.selectionForCompositeField "customer" [] object____ (Basics.identity >> Decode.nullable)


{-| A newly created customer access token object for the customer.
-}
customerAccessToken :
    SelectionSet decodesTo Shopify.Object.CustomerAccessToken
    -> SelectionSet (Maybe decodesTo) Shopify.Object.CustomerResetByUrlPayload
customerAccessToken object____ =
    Object.selectionForCompositeField "customerAccessToken" [] object____ (Basics.identity >> Decode.nullable)


{-| The list of errors that occurred from executing the mutation.
-}
customerUserErrors :
    SelectionSet decodesTo Shopify.Object.CustomerUserError
    -> SelectionSet (List decodesTo) Shopify.Object.CustomerResetByUrlPayload
customerUserErrors object____ =
    Object.selectionForCompositeField "customerUserErrors" [] object____ (Basics.identity >> Decode.list)


{-| The list of errors that occurred from executing the mutation.
-}
userErrors :
    SelectionSet decodesTo Shopify.Object.UserError
    -> SelectionSet (List decodesTo) Shopify.Object.CustomerResetByUrlPayload
userErrors object____ =
    Object.selectionForCompositeField "userErrors" [] object____ (Basics.identity >> Decode.list)
