-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.DiscountCodeApplication exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.DiscountApplicationAllocationMethod
import Shopify.Enum.DiscountApplicationTargetSelection
import Shopify.Enum.DiscountApplicationTargetType
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The method by which the discount's value is allocated to its entitled items.
-}
allocationMethod : SelectionSet Shopify.Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod Shopify.Object.DiscountCodeApplication
allocationMethod =
    Object.selectionForField "Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod" "allocationMethod" [] Shopify.Enum.DiscountApplicationAllocationMethod.decoder


{-| Specifies whether the discount code was applied successfully.
-}
applicable : SelectionSet Bool Shopify.Object.DiscountCodeApplication
applicable =
    Object.selectionForField "Bool" "applicable" [] Decode.bool


{-| The string identifying the discount code that was used at the time of application.
-}
code : SelectionSet String Shopify.Object.DiscountCodeApplication
code =
    Object.selectionForField "String" "code" [] Decode.string


{-| Which lines of targetType that the discount is allocated over.
-}
targetSelection : SelectionSet Shopify.Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection Shopify.Object.DiscountCodeApplication
targetSelection =
    Object.selectionForField "Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection" "targetSelection" [] Shopify.Enum.DiscountApplicationTargetSelection.decoder


{-| The type of line that the discount is applicable towards.
-}
targetType : SelectionSet Shopify.Enum.DiscountApplicationTargetType.DiscountApplicationTargetType Shopify.Object.DiscountCodeApplication
targetType =
    Object.selectionForField "Enum.DiscountApplicationTargetType.DiscountApplicationTargetType" "targetType" [] Shopify.Enum.DiscountApplicationTargetType.decoder


{-| The value of the discount application.
-}
value :
    SelectionSet decodesTo Shopify.Union.PricingValue
    -> SelectionSet decodesTo Shopify.Object.DiscountCodeApplication
value object____ =
    Object.selectionForCompositeField "value" [] object____ Basics.identity
