-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Domain exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The host name of the domain (eg: `example.com`).
-}
host : SelectionSet String Shopify.Object.Domain
host =
    Object.selectionForField "String" "host" [] Decode.string


{-| Whether SSL is enabled or not.
-}
sslEnabled : SelectionSet Bool Shopify.Object.Domain
sslEnabled =
    Object.selectionForField "Bool" "sslEnabled" [] Decode.bool


{-| The URL of the domain (eg: `https://example.com`).
-}
url : SelectionSet Shopify.ScalarCodecs.Url Shopify.Object.Domain
url =
    Object.selectionForField "ScalarCodecs.Url" "url" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecUrl |> .decoder)
