-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.FilterValue exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The number of results that match this filter value.
-}
count : SelectionSet Int Shopify.Object.FilterValue
count =
    Object.selectionForField "Int" "count" [] Decode.int


{-| A unique identifier.
-}
id : SelectionSet String Shopify.Object.FilterValue
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| An input object that can be used to filter by this value on the parent field.

The value is provided as a helper for building dynamic filtering UI. For example, if you have a list of selected `FilterValue` objects, you can combine their respective `input` values to use in a subsequent query.

-}
input : SelectionSet Shopify.ScalarCodecs.Json Shopify.Object.FilterValue
input =
    Object.selectionForField "ScalarCodecs.Json" "input" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecJson |> .decoder)


{-| A human-friendly string for this filter value.
-}
label : SelectionSet String Shopify.Object.FilterValue
label =
    Object.selectionForField "String" "label" [] Decode.string
