-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.FulfillmentLineItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The associated order's line item.
-}
lineItem :
    SelectionSet decodesTo Shopify.Object.OrderLineItem
    -> SelectionSet decodesTo Shopify.Object.FulfillmentLineItem
lineItem object____ =
    Object.selectionForCompositeField "lineItem" [] object____ Basics.identity


{-| The amount fulfilled in this fulfillment.
-}
quantity : SelectionSet Int Shopify.Object.FulfillmentLineItem
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int
