-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.FulfillmentTrackingInfo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The tracking number of the fulfillment.
-}
number : SelectionSet (Maybe String) Shopify.Object.FulfillmentTrackingInfo
number =
    Object.selectionForField "(Maybe String)" "number" [] (Decode.string |> Decode.nullable)


{-| The URL to track the fulfillment.
-}
url : SelectionSet (Maybe Shopify.ScalarCodecs.Url) Shopify.Object.FulfillmentTrackingInfo
url =
    Object.selectionForField "(Maybe ScalarCodecs.Url)" "url" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecUrl |> .decoder |> Decode.nullable)
