-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.GenericFile exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| A word or phrase to indicate the contents of a file.
-}
alt : SelectionSet (Maybe String) Shopify.Object.GenericFile
alt =
    Object.selectionForField "(Maybe String)" "alt" [] (Decode.string |> Decode.nullable)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.GenericFile
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The MIME type of the file.
-}
mimeType : SelectionSet (Maybe String) Shopify.Object.GenericFile
mimeType =
    Object.selectionForField "(Maybe String)" "mimeType" [] (Decode.string |> Decode.nullable)


{-| The size of the original file in bytes.
-}
originalFileSize : SelectionSet (Maybe Int) Shopify.Object.GenericFile
originalFileSize =
    Object.selectionForField "(Maybe Int)" "originalFileSize" [] (Decode.int |> Decode.nullable)


{-| The preview image for the file.
-}
previewImage :
    SelectionSet decodesTo Shopify.Object.Image
    -> SelectionSet (Maybe decodesTo) Shopify.Object.GenericFile
previewImage object____ =
    Object.selectionForCompositeField "previewImage" [] object____ (Basics.identity >> Decode.nullable)


{-| The URL of the file.
-}
url : SelectionSet (Maybe Shopify.ScalarCodecs.Url) Shopify.Object.GenericFile
url =
    Object.selectionForField "(Maybe ScalarCodecs.Url)" "url" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecUrl |> .decoder |> Decode.nullable)
