-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Language exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.LanguageCode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The name of the language in the language itself. If the language uses capitalization, it is capitalized for a mid-sentence position.
-}
endonymName : SelectionSet String Shopify.Object.Language
endonymName =
    Object.selectionForField "String" "endonymName" [] Decode.string


{-| The ISO code.
-}
isoCode : SelectionSet Shopify.Enum.LanguageCode.LanguageCode Shopify.Object.Language
isoCode =
    Object.selectionForField "Enum.LanguageCode.LanguageCode" "isoCode" [] Shopify.Enum.LanguageCode.decoder


{-| The name of the language in the current language.
-}
name : SelectionSet String Shopify.Object.Language
name =
    Object.selectionForField "String" "name" [] Decode.string
