-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Localization exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The list of countries with enabled localized experiences.
-}
availableCountries :
    SelectionSet decodesTo Shopify.Object.Country
    -> SelectionSet (List decodesTo) Shopify.Object.Localization
availableCountries object____ =
    Object.selectionForCompositeField "availableCountries" [] object____ (Basics.identity >> Decode.list)


{-| The list of languages available for the active country.
-}
availableLanguages :
    SelectionSet decodesTo Shopify.Object.Language
    -> SelectionSet (List decodesTo) Shopify.Object.Localization
availableLanguages object____ =
    Object.selectionForCompositeField "availableLanguages" [] object____ (Basics.identity >> Decode.list)


{-| The country of the active localized experience. Use the `@inContext` directive to change this value.
-}
country :
    SelectionSet decodesTo Shopify.Object.Country
    -> SelectionSet decodesTo Shopify.Object.Localization
country object____ =
    Object.selectionForCompositeField "country" [] object____ Basics.identity


{-| The language of the active localized experience. Use the `@inContext` directive to change this value.
-}
language :
    SelectionSet decodesTo Shopify.Object.Language
    -> SelectionSet decodesTo Shopify.Object.Localization
language object____ =
    Object.selectionForCompositeField "language" [] object____ Basics.identity
