-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.MailingAddress exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.CountryCode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The first line of the address. Typically the street address or PO Box number.
-}
address1 : SelectionSet (Maybe String) Shopify.Object.MailingAddress
address1 =
    Object.selectionForField "(Maybe String)" "address1" [] (Decode.string |> Decode.nullable)


{-| The second line of the address. Typically the number of the apartment, suite, or unit.
-}
address2 : SelectionSet (Maybe String) Shopify.Object.MailingAddress
address2 =
    Object.selectionForField "(Maybe String)" "address2" [] (Decode.string |> Decode.nullable)


{-| The name of the city, district, village, or town.
-}
city : SelectionSet (Maybe String) Shopify.Object.MailingAddress
city =
    Object.selectionForField "(Maybe String)" "city" [] (Decode.string |> Decode.nullable)


{-| The name of the customer's company or organization.
-}
company : SelectionSet (Maybe String) Shopify.Object.MailingAddress
company =
    Object.selectionForField "(Maybe String)" "company" [] (Decode.string |> Decode.nullable)


{-| The name of the country.
-}
country : SelectionSet (Maybe String) Shopify.Object.MailingAddress
country =
    Object.selectionForField "(Maybe String)" "country" [] (Decode.string |> Decode.nullable)


{-| The two-letter code for the country of the address.

For example, US.

-}
countryCode : SelectionSet (Maybe String) Shopify.Object.MailingAddress
countryCode =
    Object.selectionForField "(Maybe String)" "countryCode" [] (Decode.string |> Decode.nullable)


{-| The two-letter code for the country of the address.

For example, US.

-}
countryCodeV2 : SelectionSet (Maybe Shopify.Enum.CountryCode.CountryCode) Shopify.Object.MailingAddress
countryCodeV2 =
    Object.selectionForField "(Maybe Enum.CountryCode.CountryCode)" "countryCodeV2" [] (Shopify.Enum.CountryCode.decoder |> Decode.nullable)


{-| The first name of the customer.
-}
firstName : SelectionSet (Maybe String) Shopify.Object.MailingAddress
firstName =
    Object.selectionForField "(Maybe String)" "firstName" [] (Decode.string |> Decode.nullable)


type alias FormattedOptionalArguments =
    { withName : OptionalArgument Bool
    , withCompany : OptionalArgument Bool
    }


{-| A formatted version of the address, customized by the provided arguments.

  - withName - Whether to include the customer's name in the formatted address.
  - withCompany - Whether to include the customer's company in the formatted address.

-}
formatted :
    (FormattedOptionalArguments -> FormattedOptionalArguments)
    -> SelectionSet (List String) Shopify.Object.MailingAddress
formatted fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { withName = Absent, withCompany = Absent }

        optionalArgs____ =
            [ Argument.optional "withName" filledInOptionals____.withName Encode.bool, Argument.optional "withCompany" filledInOptionals____.withCompany Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "(List String)" "formatted" optionalArgs____ (Decode.string |> Decode.list)


{-| A comma-separated list of the values for city, province, and country.
-}
formattedArea : SelectionSet (Maybe String) Shopify.Object.MailingAddress
formattedArea =
    Object.selectionForField "(Maybe String)" "formattedArea" [] (Decode.string |> Decode.nullable)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.MailingAddress
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The last name of the customer.
-}
lastName : SelectionSet (Maybe String) Shopify.Object.MailingAddress
lastName =
    Object.selectionForField "(Maybe String)" "lastName" [] (Decode.string |> Decode.nullable)


{-| The latitude coordinate of the customer address.
-}
latitude : SelectionSet (Maybe Float) Shopify.Object.MailingAddress
latitude =
    Object.selectionForField "(Maybe Float)" "latitude" [] (Decode.float |> Decode.nullable)


{-| The longitude coordinate of the customer address.
-}
longitude : SelectionSet (Maybe Float) Shopify.Object.MailingAddress
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


{-| The full name of the customer, based on firstName and lastName.
-}
name : SelectionSet (Maybe String) Shopify.Object.MailingAddress
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| A unique phone number for the customer.

Formatted using E.164 standard. For example, _+16135551111_.

-}
phone : SelectionSet (Maybe String) Shopify.Object.MailingAddress
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


{-| The region of the address, such as the province, state, or district.
-}
province : SelectionSet (Maybe String) Shopify.Object.MailingAddress
province =
    Object.selectionForField "(Maybe String)" "province" [] (Decode.string |> Decode.nullable)


{-| The two-letter code for the region.

For example, ON.

-}
provinceCode : SelectionSet (Maybe String) Shopify.Object.MailingAddress
provinceCode =
    Object.selectionForField "(Maybe String)" "provinceCode" [] (Decode.string |> Decode.nullable)


{-| The zip or postal code of the address.
-}
zip : SelectionSet (Maybe String) Shopify.Object.MailingAddress
zip =
    Object.selectionForField "(Maybe String)" "zip" [] (Decode.string |> Decode.nullable)
