-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.ManualDiscountApplication exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.DiscountApplicationAllocationMethod
import Shopify.Enum.DiscountApplicationTargetSelection
import Shopify.Enum.DiscountApplicationTargetType
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The method by which the discount's value is allocated to its entitled items.
-}
allocationMethod : SelectionSet Shopify.Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod Shopify.Object.ManualDiscountApplication
allocationMethod =
    Object.selectionForField "Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod" "allocationMethod" [] Shopify.Enum.DiscountApplicationAllocationMethod.decoder


{-| The description of the application.
-}
description : SelectionSet (Maybe String) Shopify.Object.ManualDiscountApplication
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| Which lines of targetType that the discount is allocated over.
-}
targetSelection : SelectionSet Shopify.Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection Shopify.Object.ManualDiscountApplication
targetSelection =
    Object.selectionForField "Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection" "targetSelection" [] Shopify.Enum.DiscountApplicationTargetSelection.decoder


{-| The type of line that the discount is applicable towards.
-}
targetType : SelectionSet Shopify.Enum.DiscountApplicationTargetType.DiscountApplicationTargetType Shopify.Object.ManualDiscountApplication
targetType =
    Object.selectionForField "Enum.DiscountApplicationTargetType.DiscountApplicationTargetType" "targetType" [] Shopify.Enum.DiscountApplicationTargetType.decoder


{-| The title of the application.
-}
title : SelectionSet String Shopify.Object.ManualDiscountApplication
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The value of the discount application.
-}
value :
    SelectionSet decodesTo Shopify.Union.PricingValue
    -> SelectionSet decodesTo Shopify.Object.ManualDiscountApplication
value object____ =
    Object.selectionForCompositeField "value" [] object____ Basics.identity
