-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.MediaImage exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.MediaContentType
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| A word or phrase to share the nature or contents of a media.
-}
alt : SelectionSet (Maybe String) Shopify.Object.MediaImage
alt =
    Object.selectionForField "(Maybe String)" "alt" [] (Decode.string |> Decode.nullable)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.MediaImage
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The image for the media.
-}
image :
    SelectionSet decodesTo Shopify.Object.Image
    -> SelectionSet (Maybe decodesTo) Shopify.Object.MediaImage
image object____ =
    Object.selectionForCompositeField "image" [] object____ (Basics.identity >> Decode.nullable)


{-| The media content type.
-}
mediaContentType : SelectionSet Shopify.Enum.MediaContentType.MediaContentType Shopify.Object.MediaImage
mediaContentType =
    Object.selectionForField "Enum.MediaContentType.MediaContentType" "mediaContentType" [] Shopify.Enum.MediaContentType.decoder


{-| The preview image for the media.
-}
previewImage :
    SelectionSet decodesTo Shopify.Object.Image
    -> SelectionSet (Maybe decodesTo) Shopify.Object.MediaImage
previewImage object____ =
    Object.selectionForCompositeField "previewImage" [] object____ (Basics.identity >> Decode.nullable)
