-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Menu exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The menu's handle.
-}
handle : SelectionSet String Shopify.Object.Menu
handle =
    Object.selectionForField "String" "handle" [] Decode.string


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.Menu
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The menu's child items.
-}
items :
    SelectionSet decodesTo Shopify.Object.MenuItem
    -> SelectionSet (List decodesTo) Shopify.Object.Menu
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)


{-| The count of items on the menu.
-}
itemsCount : SelectionSet Int Shopify.Object.Menu
itemsCount =
    Object.selectionForField "Int" "itemsCount" [] Decode.int


{-| The menu's title.
-}
title : SelectionSet String Shopify.Object.Menu
title =
    Object.selectionForField "String" "title" [] Decode.string
