-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Metafield exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The date and time when the storefront metafield was created.
-}
createdAt : SelectionSet Shopify.ScalarCodecs.DateTime Shopify.Object.Metafield
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The description of a metafield.
-}
description : SelectionSet (Maybe String) Shopify.Object.Metafield
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.Metafield
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The key name for a metafield.
-}
key : SelectionSet String Shopify.Object.Metafield
key =
    Object.selectionForField "String" "key" [] Decode.string


{-| The namespace for a metafield.
-}
namespace : SelectionSet String Shopify.Object.Metafield
namespace =
    Object.selectionForField "String" "namespace" [] Decode.string


{-| The parent object that the metafield belongs to.
-}
parentResource :
    SelectionSet decodesTo Shopify.Union.MetafieldParentResource
    -> SelectionSet decodesTo Shopify.Object.Metafield
parentResource object____ =
    Object.selectionForCompositeField "parentResource" [] object____ Basics.identity


{-| Returns a reference object if the metafield definition's type is a resource reference.
-}
reference :
    SelectionSet decodesTo Shopify.Union.MetafieldReference
    -> SelectionSet (Maybe decodesTo) Shopify.Object.Metafield
reference object____ =
    Object.selectionForCompositeField "reference" [] object____ (Basics.identity >> Decode.nullable)


{-| The type name of the metafield.
See the list of [supported types](https://shopify.dev/apps/metafields/definitions/types).
-}
type_ : SelectionSet String Shopify.Object.Metafield
type_ =
    Object.selectionForField "String" "type" [] Decode.string


{-| The date and time when the storefront metafield was updated.
-}
updatedAt : SelectionSet Shopify.ScalarCodecs.DateTime Shopify.Object.Metafield
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The value of a metafield.
-}
value : SelectionSet String Shopify.Object.Metafield
value =
    Object.selectionForField "String" "value" [] Decode.string
