-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Model3dSource exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The filesize of the 3d model.
-}
filesize : SelectionSet Int Shopify.Object.Model3dSource
filesize =
    Object.selectionForField "Int" "filesize" [] Decode.int


{-| The format of the 3d model.
-}
format : SelectionSet String Shopify.Object.Model3dSource
format =
    Object.selectionForField "String" "format" [] Decode.string


{-| The MIME type of the 3d model.
-}
mimeType : SelectionSet String Shopify.Object.Model3dSource
mimeType =
    Object.selectionForField "String" "mimeType" [] Decode.string


{-| The URL of the 3d model.
-}
url : SelectionSet String Shopify.Object.Model3dSource
url =
    Object.selectionForField "String" "url" [] Decode.string
