-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.MoneyV2 exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.CurrencyCode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| Decimal money amount.
-}
amount : SelectionSet Shopify.ScalarCodecs.Decimal Shopify.Object.MoneyV2
amount =
    Object.selectionForField "ScalarCodecs.Decimal" "amount" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


{-| Currency of the money.
-}
currencyCode : SelectionSet Shopify.Enum.CurrencyCode.CurrencyCode Shopify.Object.MoneyV2
currencyCode =
    Object.selectionForField "Enum.CurrencyCode.CurrencyCode" "currencyCode" [] Shopify.Enum.CurrencyCode.decoder
