-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.OrderLineItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The number of entries associated to the line item minus the items that have been removed.
-}
currentQuantity : SelectionSet Int Shopify.Object.OrderLineItem
currentQuantity =
    Object.selectionForField "Int" "currentQuantity" [] Decode.int


{-| List of custom attributes associated to the line item.
-}
customAttributes :
    SelectionSet decodesTo Shopify.Object.Attribute
    -> SelectionSet (List decodesTo) Shopify.Object.OrderLineItem
customAttributes object____ =
    Object.selectionForCompositeField "customAttributes" [] object____ (Basics.identity >> Decode.list)


{-| The discounts that have been allocated onto the order line item by discount applications.
-}
discountAllocations :
    SelectionSet decodesTo Shopify.Object.DiscountAllocation
    -> SelectionSet (List decodesTo) Shopify.Object.OrderLineItem
discountAllocations object____ =
    Object.selectionForCompositeField "discountAllocations" [] object____ (Basics.identity >> Decode.list)


{-| The total price of the line item, including discounts, and displayed in the presentment currency.
-}
discountedTotalPrice :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.OrderLineItem
discountedTotalPrice object____ =
    Object.selectionForCompositeField "discountedTotalPrice" [] object____ Basics.identity


{-| The total price of the line item, not including any discounts. The total price is calculated using the original unit price multiplied by the quantity, and it is displayed in the presentment currency.
-}
originalTotalPrice :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.OrderLineItem
originalTotalPrice object____ =
    Object.selectionForCompositeField "originalTotalPrice" [] object____ Basics.identity


{-| The number of products variants associated to the line item.
-}
quantity : SelectionSet Int Shopify.Object.OrderLineItem
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int


{-| The title of the product combined with title of the variant.
-}
title : SelectionSet String Shopify.Object.OrderLineItem
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The product variant object associated to the line item.
-}
variant :
    SelectionSet decodesTo Shopify.Object.ProductVariant
    -> SelectionSet (Maybe decodesTo) Shopify.Object.OrderLineItem
variant object____ =
    Object.selectionForCompositeField "variant" [] object____ (Basics.identity >> Decode.nullable)
