-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.PaymentSettings exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.CardBrand
import Shopify.Enum.CountryCode
import Shopify.Enum.CurrencyCode
import Shopify.Enum.DigitalWallet
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| List of the card brands which the shop accepts.
-}
acceptedCardBrands : SelectionSet (List Shopify.Enum.CardBrand.CardBrand) Shopify.Object.PaymentSettings
acceptedCardBrands =
    Object.selectionForField "(List Enum.CardBrand.CardBrand)" "acceptedCardBrands" [] (Shopify.Enum.CardBrand.decoder |> Decode.list)


{-| The url pointing to the endpoint to vault credit cards.
-}
cardVaultUrl : SelectionSet Shopify.ScalarCodecs.Url Shopify.Object.PaymentSettings
cardVaultUrl =
    Object.selectionForField "ScalarCodecs.Url" "cardVaultUrl" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecUrl |> .decoder)


{-| The country where the shop is located.
-}
countryCode : SelectionSet Shopify.Enum.CountryCode.CountryCode Shopify.Object.PaymentSettings
countryCode =
    Object.selectionForField "Enum.CountryCode.CountryCode" "countryCode" [] Shopify.Enum.CountryCode.decoder


{-| The three-letter code for the shop's primary currency.
-}
currencyCode : SelectionSet Shopify.Enum.CurrencyCode.CurrencyCode Shopify.Object.PaymentSettings
currencyCode =
    Object.selectionForField "Enum.CurrencyCode.CurrencyCode" "currencyCode" [] Shopify.Enum.CurrencyCode.decoder


{-| A list of enabled currencies (ISO 4217 format) that the shop accepts. Merchants can enable currencies from their Shopify Payments settings in the Shopify admin.
-}
enabledPresentmentCurrencies : SelectionSet (List Shopify.Enum.CurrencyCode.CurrencyCode) Shopify.Object.PaymentSettings
enabledPresentmentCurrencies =
    Object.selectionForField "(List Enum.CurrencyCode.CurrencyCode)" "enabledPresentmentCurrencies" [] (Shopify.Enum.CurrencyCode.decoder |> Decode.list)


{-| The shop’s Shopify Payments account id.
-}
shopifyPaymentsAccountId : SelectionSet (Maybe String) Shopify.Object.PaymentSettings
shopifyPaymentsAccountId =
    Object.selectionForField "(Maybe String)" "shopifyPaymentsAccountId" [] (Decode.string |> Decode.nullable)


{-| List of the digital wallets which the shop supports.
-}
supportedDigitalWallets : SelectionSet (List Shopify.Enum.DigitalWallet.DigitalWallet) Shopify.Object.PaymentSettings
supportedDigitalWallets =
    Object.selectionForField "(List Enum.DigitalWallet.DigitalWallet)" "supportedDigitalWallets" [] (Shopify.Enum.DigitalWallet.decoder |> Decode.list)
