-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.SellingPlan exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The initial payment due for the purchase.
-}
checkoutCharge :
    SelectionSet decodesTo Shopify.Object.SellingPlanCheckoutCharge
    -> SelectionSet decodesTo Shopify.Object.SellingPlan
checkoutCharge object____ =
    Object.selectionForCompositeField "checkoutCharge" [] object____ Basics.identity


{-| The description of the selling plan.
-}
description : SelectionSet (Maybe String) Shopify.Object.SellingPlan
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| A globally-unique identifier.
-}
id : SelectionSet Shopify.ScalarCodecs.Id Shopify.Object.SellingPlan
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the selling plan. For example, '6 weeks of prepaid granola, delivered weekly'.
-}
name : SelectionSet String Shopify.Object.SellingPlan
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The selling plan options available in the drop-down list in the storefront. For example, 'Delivery every week' or 'Delivery every 2 weeks' specifies the delivery frequency options for the product.
-}
options :
    SelectionSet decodesTo Shopify.Object.SellingPlanOption
    -> SelectionSet (List decodesTo) Shopify.Object.SellingPlan
options object____ =
    Object.selectionForCompositeField "options" [] object____ (Basics.identity >> Decode.list)


{-| The price adjustments that a selling plan makes when a variant is purchased with a selling plan.
-}
priceAdjustments :
    SelectionSet decodesTo Shopify.Object.SellingPlanPriceAdjustment
    -> SelectionSet (List decodesTo) Shopify.Object.SellingPlan
priceAdjustments object____ =
    Object.selectionForCompositeField "priceAdjustments" [] object____ (Basics.identity >> Decode.list)


{-| Whether purchasing the selling plan will result in multiple deliveries.
-}
recurringDeliveries : SelectionSet Bool Shopify.Object.SellingPlan
recurringDeliveries =
    Object.selectionForField "Bool" "recurringDeliveries" [] Decode.bool
