-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.SellingPlanGroupOption exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The name of the option. For example, 'Delivery every'.
-}
name : SelectionSet String Shopify.Object.SellingPlanGroupOption
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The values for the options specified by the selling plans in the selling plan group. For example, '1 week', '2 weeks', '3 weeks'.
-}
values : SelectionSet (List String) Shopify.Object.SellingPlanGroupOption
values =
    Object.selectionForField "(List String)" "values" [] (Decode.string |> Decode.list)
