-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.ShopPolicyWithDefault exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The text of the policy. Maximum size: 64KB.
-}
body : SelectionSet String Shopify.Object.ShopPolicyWithDefault
body =
    Object.selectionForField "String" "body" [] Decode.string


{-| The handle of the policy.
-}
handle : SelectionSet String Shopify.Object.ShopPolicyWithDefault
handle =
    Object.selectionForField "String" "handle" [] Decode.string


{-| The unique identifier of the policy. A default policy doesn't have an ID.
-}
id : SelectionSet (Maybe Shopify.ScalarCodecs.Id) Shopify.Object.ShopPolicyWithDefault
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| The title of the policy.
-}
title : SelectionSet String Shopify.Object.ShopPolicyWithDefault
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| Public URL to the policy.
-}
url : SelectionSet Shopify.ScalarCodecs.Url Shopify.Object.ShopPolicyWithDefault
url =
    Object.selectionForField "ScalarCodecs.Url" "url" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecUrl |> .decoder)
