-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.Transaction exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.TransactionKind
import Shopify.Enum.TransactionStatus
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The amount of money that the transaction was for.
-}
amount : SelectionSet Shopify.ScalarCodecs.Money Shopify.Object.Transaction
amount =
    Object.selectionForField "ScalarCodecs.Money" "amount" [] (Shopify.ScalarCodecs.codecs |> Shopify.Scalar.unwrapCodecs |> .codecMoney |> .decoder)


{-| The amount of money that the transaction was for.
-}
amountV2 :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Object.Transaction
amountV2 object____ =
    Object.selectionForCompositeField "amountV2" [] object____ Basics.identity


{-| The kind of the transaction.
-}
kind : SelectionSet Shopify.Enum.TransactionKind.TransactionKind Shopify.Object.Transaction
kind =
    Object.selectionForField "Enum.TransactionKind.TransactionKind" "kind" [] Shopify.Enum.TransactionKind.decoder


{-| The status of the transaction.
-}
status : SelectionSet Shopify.Enum.TransactionStatus.TransactionStatus Shopify.Object.Transaction
status =
    Object.selectionForField "Enum.TransactionStatus.TransactionStatus" "status" [] Shopify.Enum.TransactionStatus.decoder


{-| The status of the transaction.
-}
statusV2 : SelectionSet (Maybe Shopify.Enum.TransactionStatus.TransactionStatus) Shopify.Object.Transaction
statusV2 =
    Object.selectionForField "(Maybe Enum.TransactionStatus.TransactionStatus)" "statusV2" [] (Shopify.Enum.TransactionStatus.decoder |> Decode.nullable)


{-| Whether the transaction was done in test mode or not.
-}
test : SelectionSet Bool Shopify.Object.Transaction
test =
    Object.selectionForField "Bool" "test" [] Decode.bool
