-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Object.UnitPriceMeasurement exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shopify.Enum.UnitPriceMeasurementMeasuredType
import Shopify.Enum.UnitPriceMeasurementMeasuredUnit
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


{-| The type of unit of measurement for the unit price measurement.
-}
measuredType : SelectionSet (Maybe Shopify.Enum.UnitPriceMeasurementMeasuredType.UnitPriceMeasurementMeasuredType) Shopify.Object.UnitPriceMeasurement
measuredType =
    Object.selectionForField "(Maybe Enum.UnitPriceMeasurementMeasuredType.UnitPriceMeasurementMeasuredType)" "measuredType" [] (Shopify.Enum.UnitPriceMeasurementMeasuredType.decoder |> Decode.nullable)


{-| The quantity unit for the unit price measurement.
-}
quantityUnit : SelectionSet (Maybe Shopify.Enum.UnitPriceMeasurementMeasuredUnit.UnitPriceMeasurementMeasuredUnit) Shopify.Object.UnitPriceMeasurement
quantityUnit =
    Object.selectionForField "(Maybe Enum.UnitPriceMeasurementMeasuredUnit.UnitPriceMeasurementMeasuredUnit)" "quantityUnit" [] (Shopify.Enum.UnitPriceMeasurementMeasuredUnit.decoder |> Decode.nullable)


{-| The quantity value for the unit price measurement.
-}
quantityValue : SelectionSet Float Shopify.Object.UnitPriceMeasurement
quantityValue =
    Object.selectionForField "Float" "quantityValue" [] Decode.float


{-| The reference unit for the unit price measurement.
-}
referenceUnit : SelectionSet (Maybe Shopify.Enum.UnitPriceMeasurementMeasuredUnit.UnitPriceMeasurementMeasuredUnit) Shopify.Object.UnitPriceMeasurement
referenceUnit =
    Object.selectionForField "(Maybe Enum.UnitPriceMeasurementMeasuredUnit.UnitPriceMeasurementMeasuredUnit)" "referenceUnit" [] (Shopify.Enum.UnitPriceMeasurementMeasuredUnit.decoder |> Decode.nullable)


{-| The reference value for the unit price measurement.
-}
referenceValue : SelectionSet Int Shopify.Object.UnitPriceMeasurement
referenceValue =
    Object.selectionForField "Int" "referenceValue" [] Decode.int
