-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.CountryCode exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The code designating a country/region, which generally follows ISO 3166-1 alpha-2 guidelines.
If a territory doesn't have a country code value in the `CountryCode` enum, then it might be considered a subdivision
of another country. For example, the territories associated with Spain are represented by the country code `ES`,
and the territories associated with the United States of America are represented by the country code `US`.

  - Af - Afghanistan.
  - Ax - Åland Islands.
  - Al - Albania.
  - Dz - Algeria.
  - Ad - Andorra.
  - Ao - Angola.
  - Ai - Anguilla.
  - Ag - Antigua & Barbuda.
  - Ar - Argentina.
  - Am - Armenia.
  - Aw - Aruba.
  - Ac - Ascension Island.
  - Au - Australia.
  - At - Austria.
  - Az - Azerbaijan.
  - Bs - Bahamas.
  - Bh - Bahrain.
  - Bd - Bangladesh.
  - Bb - Barbados.
  - By - Belarus.
  - Be - Belgium.
  - Bz - Belize.
  - Bj - Benin.
  - Bm - Bermuda.
  - Bt - Bhutan.
  - Bo - Bolivia.
  - Ba - Bosnia & Herzegovina.
  - Bw - Botswana.
  - Bv - Bouvet Island.
  - Br - Brazil.
  - Io - British Indian Ocean Territory.
  - Bn - Brunei.
  - Bg - Bulgaria.
  - Bf - Burkina Faso.
  - Bi - Burundi.
  - Kh - Cambodia.
  - Ca - Canada.
  - Cv - Cape Verde.
  - Bq - Caribbean Netherlands.
  - Ky - Cayman Islands.
  - Cf - Central African Republic.
  - Td - Chad.
  - Cl - Chile.
  - Cn - China.
  - Cx - Christmas Island.
  - Cc - Cocos (Keeling) Islands.
  - Co - Colombia.
  - Km - Comoros.
  - Cg - Congo - Brazzaville.
  - Cd - Congo - Kinshasa.
  - Ck - Cook Islands.
  - Cr - Costa Rica.
  - Hr - Croatia.
  - Cu - Cuba.
  - Cw - Curaçao.
  - Cy - Cyprus.
  - Cz - Czechia.
  - Ci - Côte d’Ivoire.
  - Dk - Denmark.
  - Dj - Djibouti.
  - Dm - Dominica.
  - Do - Dominican Republic.
  - Ec - Ecuador.
  - Eg - Egypt.
  - Sv - El Salvador.
  - Gq - Equatorial Guinea.
  - Er - Eritrea.
  - Ee - Estonia.
  - Sz - Eswatini.
  - Et - Ethiopia.
  - Fk - Falkland Islands.
  - Fo - Faroe Islands.
  - Fj - Fiji.
  - Fi - Finland.
  - Fr - France.
  - Gf - French Guiana.
  - Pf - French Polynesia.
  - Tf - French Southern Territories.
  - Ga - Gabon.
  - Gm - Gambia.
  - Ge - Georgia.
  - De - Germany.
  - Gh - Ghana.
  - Gi - Gibraltar.
  - Gr - Greece.
  - Gl - Greenland.
  - Gd - Grenada.
  - Gp - Guadeloupe.
  - Gt - Guatemala.
  - Gg - Guernsey.
  - Gn - Guinea.
  - Gw - Guinea-Bissau.
  - Gy - Guyana.
  - Ht - Haiti.
  - Hm - Heard & McDonald Islands.
  - Va - Vatican City.
  - Hn - Honduras.
  - Hk - Hong Kong SAR.
  - Hu - Hungary.
  - Is - Iceland.
  - In - India.
  - Id - Indonesia.
  - Ir - Iran.
  - Iq - Iraq.
  - Ie - Ireland.
  - Im - Isle of Man.
  - Il - Israel.
  - It - Italy.
  - Jm - Jamaica.
  - Jp - Japan.
  - Je - Jersey.
  - Jo - Jordan.
  - Kz - Kazakhstan.
  - Ke - Kenya.
  - Ki - Kiribati.
  - Kp - North Korea.
  - Xk - Kosovo.
  - Kw - Kuwait.
  - Kg - Kyrgyzstan.
  - La - Laos.
  - Lv - Latvia.
  - Lb - Lebanon.
  - Ls - Lesotho.
  - Lr - Liberia.
  - Ly - Libya.
  - Li - Liechtenstein.
  - Lt - Lithuania.
  - Lu - Luxembourg.
  - Mo - Macao SAR.
  - Mg - Madagascar.
  - Mw - Malawi.
  - My - Malaysia.
  - Mv - Maldives.
  - Ml - Mali.
  - Mt - Malta.
  - Mq - Martinique.
  - Mr - Mauritania.
  - Mu - Mauritius.
  - Yt - Mayotte.
  - Mx - Mexico.
  - Md - Moldova.
  - Mc - Monaco.
  - Mn - Mongolia.
  - Me - Montenegro.
  - Ms - Montserrat.
  - Ma - Morocco.
  - Mz - Mozambique.
  - Mm - Myanmar (Burma).
  - Na - Namibia.
  - Nr - Nauru.
  - Np - Nepal.
  - Nl - Netherlands.
  - An - Netherlands Antilles.
  - Nc - New Caledonia.
  - Nz - New Zealand.
  - Ni - Nicaragua.
  - Ne - Niger.
  - Ng - Nigeria.
  - Nu - Niue.
  - Nf - Norfolk Island.
  - Mk - North Macedonia.
  - No - Norway.
  - Om - Oman.
  - Pk - Pakistan.
  - Ps - Palestinian Territories.
  - Pa - Panama.
  - Pg - Papua New Guinea.
  - Py - Paraguay.
  - Pe - Peru.
  - Ph - Philippines.
  - Pn - Pitcairn Islands.
  - Pl - Poland.
  - Pt - Portugal.
  - Qa - Qatar.
  - Cm - Cameroon.
  - Re - Réunion.
  - Ro - Romania.
  - Ru - Russia.
  - Rw - Rwanda.
  - Bl - St. Barthélemy.
  - Sh - St. Helena.
  - Kn - St. Kitts & Nevis.
  - Lc - St. Lucia.
  - Mf - St. Martin.
  - Pm - St. Pierre & Miquelon.
  - Ws - Samoa.
  - Sm - San Marino.
  - St - São Tomé & Príncipe.
  - Sa - Saudi Arabia.
  - Sn - Senegal.
  - Rs - Serbia.
  - Sc - Seychelles.
  - Sl - Sierra Leone.
  - Sg - Singapore.
  - Sx - Sint Maarten.
  - Sk - Slovakia.
  - Si - Slovenia.
  - Sb - Solomon Islands.
  - So - Somalia.
  - Za - South Africa.
  - Gs - South Georgia & South Sandwich Islands.
  - Kr - South Korea.
  - Ss - South Sudan.
  - Es - Spain.
  - Lk - Sri Lanka.
  - Vc - St. Vincent & Grenadines.
  - Sd - Sudan.
  - Sr - Suriname.
  - Sj - Svalbard & Jan Mayen.
  - Se - Sweden.
  - Ch - Switzerland.
  - Sy - Syria.
  - Tw - Taiwan.
  - Tj - Tajikistan.
  - Tz - Tanzania.
  - Th - Thailand.
  - Tl - Timor-Leste.
  - Tg - Togo.
  - Tk - Tokelau.
  - To - Tonga.
  - Tt - Trinidad & Tobago.
  - Ta - Tristan da Cunha.
  - Tn - Tunisia.
  - Tr - Turkey.
  - Tm - Turkmenistan.
  - Tc - Turks & Caicos Islands.
  - Tv - Tuvalu.
  - Ug - Uganda.
  - Ua - Ukraine.
  - Ae - United Arab Emirates.
  - Gb - United Kingdom.
  - Us - United States.
  - Um - U.S. Outlying Islands.
  - Uy - Uruguay.
  - Uz - Uzbekistan.
  - Vu - Vanuatu.
  - Ve - Venezuela.
  - Vn - Vietnam.
  - Vg - British Virgin Islands.
  - Wf - Wallis & Futuna.
  - Eh - Western Sahara.
  - Ye - Yemen.
  - Zm - Zambia.
  - Zw - Zimbabwe.
  - Zz - Unknown Region.

-}
type CountryCode
    = Af
    | Ax
    | Al
    | Dz
    | Ad
    | Ao
    | Ai
    | Ag
    | Ar
    | Am
    | Aw
    | Ac
    | Au
    | At
    | Az
    | Bs
    | Bh
    | Bd
    | Bb
    | By
    | Be
    | Bz
    | Bj
    | Bm
    | Bt
    | Bo
    | Ba
    | Bw
    | Bv
    | Br
    | Io
    | Bn
    | Bg
    | Bf
    | Bi
    | Kh
    | Ca
    | Cv
    | Bq
    | Ky
    | Cf
    | Td
    | Cl
    | Cn
    | Cx
    | Cc
    | Co
    | Km
    | Cg
    | Cd
    | Ck
    | Cr
    | Hr
    | Cu
    | Cw
    | Cy
    | Cz
    | Ci
    | Dk
    | Dj
    | Dm
    | Do
    | Ec
    | Eg
    | Sv
    | Gq
    | Er
    | Ee
    | Sz
    | Et
    | Fk
    | Fo
    | Fj
    | Fi
    | Fr
    | Gf
    | Pf
    | Tf
    | Ga
    | Gm
    | Ge
    | De
    | Gh
    | Gi
    | Gr
    | Gl
    | Gd
    | Gp
    | Gt
    | Gg
    | Gn
    | Gw
    | Gy
    | Ht
    | Hm
    | Va
    | Hn
    | Hk
    | Hu
    | Is
    | In
    | Id
    | Ir
    | Iq
    | Ie
    | Im
    | Il
    | It
    | Jm
    | Jp
    | Je
    | Jo
    | Kz
    | Ke
    | Ki
    | Kp
    | Xk
    | Kw
    | Kg
    | La
    | Lv
    | Lb
    | Ls
    | Lr
    | Ly
    | Li
    | Lt
    | Lu
    | Mo
    | Mg
    | Mw
    | My
    | Mv
    | Ml
    | Mt
    | Mq
    | Mr
    | Mu
    | Yt
    | Mx
    | Md
    | Mc
    | Mn
    | Me
    | Ms
    | Ma
    | Mz
    | Mm
    | Na
    | Nr
    | Np
    | Nl
    | An
    | Nc
    | Nz
    | Ni
    | Ne
    | Ng
    | Nu
    | Nf
    | Mk
    | No
    | Om
    | Pk
    | Ps
    | Pa
    | Pg
    | Py
    | Pe
    | Ph
    | Pn
    | Pl
    | Pt
    | Qa
    | Cm
    | Re
    | Ro
    | Ru
    | Rw
    | Bl
    | Sh
    | Kn
    | Lc
    | Mf
    | Pm
    | Ws
    | Sm
    | St
    | Sa
    | Sn
    | Rs
    | Sc
    | Sl
    | Sg
    | Sx
    | Sk
    | Si
    | Sb
    | So
    | Za
    | Gs
    | Kr
    | Ss
    | Es
    | Lk
    | Vc
    | Sd
    | Sr
    | Sj
    | Se
    | Ch
    | Sy
    | Tw
    | Tj
    | Tz
    | Th
    | Tl
    | Tg
    | Tk
    | To
    | Tt
    | Ta
    | Tn
    | Tr
    | Tm
    | Tc
    | Tv
    | Ug
    | Ua
    | Ae
    | Gb
    | Us
    | Um
    | Uy
    | Uz
    | Vu
    | Ve
    | Vn
    | Vg
    | Wf
    | Eh
    | Ye
    | Zm
    | Zw
    | Zz


list : List CountryCode
list =
    [ Af, Ax, Al, Dz, Ad, Ao, Ai, Ag, Ar, Am, Aw, Ac, Au, At, Az, Bs, Bh, Bd, Bb, By, Be, Bz, Bj, Bm, Bt, Bo, Ba, Bw, Bv, Br, Io, Bn, Bg, Bf, Bi, Kh, Ca, Cv, Bq, Ky, Cf, Td, Cl, Cn, Cx, Cc, Co, Km, Cg, Cd, Ck, Cr, Hr, Cu, Cw, Cy, Cz, Ci, Dk, Dj, Dm, Do, Ec, Eg, Sv, Gq, Er, Ee, Sz, Et, Fk, Fo, Fj, Fi, Fr, Gf, Pf, Tf, Ga, Gm, Ge, De, Gh, Gi, Gr, Gl, Gd, Gp, Gt, Gg, Gn, Gw, Gy, Ht, Hm, Va, Hn, Hk, Hu, Is, In, Id, Ir, Iq, Ie, Im, Il, It, Jm, Jp, Je, Jo, Kz, Ke, Ki, Kp, Xk, Kw, Kg, La, Lv, Lb, Ls, Lr, Ly, Li, Lt, Lu, Mo, Mg, Mw, My, Mv, Ml, Mt, Mq, Mr, Mu, Yt, Mx, Md, Mc, Mn, Me, Ms, Ma, Mz, Mm, Na, Nr, Np, Nl, An, Nc, Nz, Ni, Ne, Ng, Nu, Nf, Mk, No, Om, Pk, Ps, Pa, Pg, Py, Pe, Ph, Pn, Pl, Pt, Qa, Cm, Re, Ro, Ru, Rw, Bl, Sh, Kn, Lc, Mf, Pm, Ws, Sm, St, Sa, Sn, Rs, Sc, Sl, Sg, Sx, Sk, Si, Sb, So, Za, Gs, Kr, Ss, Es, Lk, Vc, Sd, Sr, Sj, Se, Ch, Sy, Tw, Tj, Tz, Th, Tl, Tg, Tk, To, Tt, Ta, Tn, Tr, Tm, Tc, Tv, Ug, Ua, Ae, Gb, Us, Um, Uy, Uz, Vu, Ve, Vn, Vg, Wf, Eh, Ye, Zm, Zw, Zz ]


decoder : Decoder CountryCode
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "AF" ->
                        Decode.succeed Af

                    "AX" ->
                        Decode.succeed Ax

                    "AL" ->
                        Decode.succeed Al

                    "DZ" ->
                        Decode.succeed Dz

                    "AD" ->
                        Decode.succeed Ad

                    "AO" ->
                        Decode.succeed Ao

                    "AI" ->
                        Decode.succeed Ai

                    "AG" ->
                        Decode.succeed Ag

                    "AR" ->
                        Decode.succeed Ar

                    "AM" ->
                        Decode.succeed Am

                    "AW" ->
                        Decode.succeed Aw

                    "AC" ->
                        Decode.succeed Ac

                    "AU" ->
                        Decode.succeed Au

                    "AT" ->
                        Decode.succeed At

                    "AZ" ->
                        Decode.succeed Az

                    "BS" ->
                        Decode.succeed Bs

                    "BH" ->
                        Decode.succeed Bh

                    "BD" ->
                        Decode.succeed Bd

                    "BB" ->
                        Decode.succeed Bb

                    "BY" ->
                        Decode.succeed By

                    "BE" ->
                        Decode.succeed Be

                    "BZ" ->
                        Decode.succeed Bz

                    "BJ" ->
                        Decode.succeed Bj

                    "BM" ->
                        Decode.succeed Bm

                    "BT" ->
                        Decode.succeed Bt

                    "BO" ->
                        Decode.succeed Bo

                    "BA" ->
                        Decode.succeed Ba

                    "BW" ->
                        Decode.succeed Bw

                    "BV" ->
                        Decode.succeed Bv

                    "BR" ->
                        Decode.succeed Br

                    "IO" ->
                        Decode.succeed Io

                    "BN" ->
                        Decode.succeed Bn

                    "BG" ->
                        Decode.succeed Bg

                    "BF" ->
                        Decode.succeed Bf

                    "BI" ->
                        Decode.succeed Bi

                    "KH" ->
                        Decode.succeed Kh

                    "CA" ->
                        Decode.succeed Ca

                    "CV" ->
                        Decode.succeed Cv

                    "BQ" ->
                        Decode.succeed Bq

                    "KY" ->
                        Decode.succeed Ky

                    "CF" ->
                        Decode.succeed Cf

                    "TD" ->
                        Decode.succeed Td

                    "CL" ->
                        Decode.succeed Cl

                    "CN" ->
                        Decode.succeed Cn

                    "CX" ->
                        Decode.succeed Cx

                    "CC" ->
                        Decode.succeed Cc

                    "CO" ->
                        Decode.succeed Co

                    "KM" ->
                        Decode.succeed Km

                    "CG" ->
                        Decode.succeed Cg

                    "CD" ->
                        Decode.succeed Cd

                    "CK" ->
                        Decode.succeed Ck

                    "CR" ->
                        Decode.succeed Cr

                    "HR" ->
                        Decode.succeed Hr

                    "CU" ->
                        Decode.succeed Cu

                    "CW" ->
                        Decode.succeed Cw

                    "CY" ->
                        Decode.succeed Cy

                    "CZ" ->
                        Decode.succeed Cz

                    "CI" ->
                        Decode.succeed Ci

                    "DK" ->
                        Decode.succeed Dk

                    "DJ" ->
                        Decode.succeed Dj

                    "DM" ->
                        Decode.succeed Dm

                    "DO" ->
                        Decode.succeed Do

                    "EC" ->
                        Decode.succeed Ec

                    "EG" ->
                        Decode.succeed Eg

                    "SV" ->
                        Decode.succeed Sv

                    "GQ" ->
                        Decode.succeed Gq

                    "ER" ->
                        Decode.succeed Er

                    "EE" ->
                        Decode.succeed Ee

                    "SZ" ->
                        Decode.succeed Sz

                    "ET" ->
                        Decode.succeed Et

                    "FK" ->
                        Decode.succeed Fk

                    "FO" ->
                        Decode.succeed Fo

                    "FJ" ->
                        Decode.succeed Fj

                    "FI" ->
                        Decode.succeed Fi

                    "FR" ->
                        Decode.succeed Fr

                    "GF" ->
                        Decode.succeed Gf

                    "PF" ->
                        Decode.succeed Pf

                    "TF" ->
                        Decode.succeed Tf

                    "GA" ->
                        Decode.succeed Ga

                    "GM" ->
                        Decode.succeed Gm

                    "GE" ->
                        Decode.succeed Ge

                    "DE" ->
                        Decode.succeed De

                    "GH" ->
                        Decode.succeed Gh

                    "GI" ->
                        Decode.succeed Gi

                    "GR" ->
                        Decode.succeed Gr

                    "GL" ->
                        Decode.succeed Gl

                    "GD" ->
                        Decode.succeed Gd

                    "GP" ->
                        Decode.succeed Gp

                    "GT" ->
                        Decode.succeed Gt

                    "GG" ->
                        Decode.succeed Gg

                    "GN" ->
                        Decode.succeed Gn

                    "GW" ->
                        Decode.succeed Gw

                    "GY" ->
                        Decode.succeed Gy

                    "HT" ->
                        Decode.succeed Ht

                    "HM" ->
                        Decode.succeed Hm

                    "VA" ->
                        Decode.succeed Va

                    "HN" ->
                        Decode.succeed Hn

                    "HK" ->
                        Decode.succeed Hk

                    "HU" ->
                        Decode.succeed Hu

                    "IS" ->
                        Decode.succeed Is

                    "IN" ->
                        Decode.succeed In

                    "ID" ->
                        Decode.succeed Id

                    "IR" ->
                        Decode.succeed Ir

                    "IQ" ->
                        Decode.succeed Iq

                    "IE" ->
                        Decode.succeed Ie

                    "IM" ->
                        Decode.succeed Im

                    "IL" ->
                        Decode.succeed Il

                    "IT" ->
                        Decode.succeed It

                    "JM" ->
                        Decode.succeed Jm

                    "JP" ->
                        Decode.succeed Jp

                    "JE" ->
                        Decode.succeed Je

                    "JO" ->
                        Decode.succeed Jo

                    "KZ" ->
                        Decode.succeed Kz

                    "KE" ->
                        Decode.succeed Ke

                    "KI" ->
                        Decode.succeed Ki

                    "KP" ->
                        Decode.succeed Kp

                    "XK" ->
                        Decode.succeed Xk

                    "KW" ->
                        Decode.succeed Kw

                    "KG" ->
                        Decode.succeed Kg

                    "LA" ->
                        Decode.succeed La

                    "LV" ->
                        Decode.succeed Lv

                    "LB" ->
                        Decode.succeed Lb

                    "LS" ->
                        Decode.succeed Ls

                    "LR" ->
                        Decode.succeed Lr

                    "LY" ->
                        Decode.succeed Ly

                    "LI" ->
                        Decode.succeed Li

                    "LT" ->
                        Decode.succeed Lt

                    "LU" ->
                        Decode.succeed Lu

                    "MO" ->
                        Decode.succeed Mo

                    "MG" ->
                        Decode.succeed Mg

                    "MW" ->
                        Decode.succeed Mw

                    "MY" ->
                        Decode.succeed My

                    "MV" ->
                        Decode.succeed Mv

                    "ML" ->
                        Decode.succeed Ml

                    "MT" ->
                        Decode.succeed Mt

                    "MQ" ->
                        Decode.succeed Mq

                    "MR" ->
                        Decode.succeed Mr

                    "MU" ->
                        Decode.succeed Mu

                    "YT" ->
                        Decode.succeed Yt

                    "MX" ->
                        Decode.succeed Mx

                    "MD" ->
                        Decode.succeed Md

                    "MC" ->
                        Decode.succeed Mc

                    "MN" ->
                        Decode.succeed Mn

                    "ME" ->
                        Decode.succeed Me

                    "MS" ->
                        Decode.succeed Ms

                    "MA" ->
                        Decode.succeed Ma

                    "MZ" ->
                        Decode.succeed Mz

                    "MM" ->
                        Decode.succeed Mm

                    "NA" ->
                        Decode.succeed Na

                    "NR" ->
                        Decode.succeed Nr

                    "NP" ->
                        Decode.succeed Np

                    "NL" ->
                        Decode.succeed Nl

                    "AN" ->
                        Decode.succeed An

                    "NC" ->
                        Decode.succeed Nc

                    "NZ" ->
                        Decode.succeed Nz

                    "NI" ->
                        Decode.succeed Ni

                    "NE" ->
                        Decode.succeed Ne

                    "NG" ->
                        Decode.succeed Ng

                    "NU" ->
                        Decode.succeed Nu

                    "NF" ->
                        Decode.succeed Nf

                    "MK" ->
                        Decode.succeed Mk

                    "NO" ->
                        Decode.succeed No

                    "OM" ->
                        Decode.succeed Om

                    "PK" ->
                        Decode.succeed Pk

                    "PS" ->
                        Decode.succeed Ps

                    "PA" ->
                        Decode.succeed Pa

                    "PG" ->
                        Decode.succeed Pg

                    "PY" ->
                        Decode.succeed Py

                    "PE" ->
                        Decode.succeed Pe

                    "PH" ->
                        Decode.succeed Ph

                    "PN" ->
                        Decode.succeed Pn

                    "PL" ->
                        Decode.succeed Pl

                    "PT" ->
                        Decode.succeed Pt

                    "QA" ->
                        Decode.succeed Qa

                    "CM" ->
                        Decode.succeed Cm

                    "RE" ->
                        Decode.succeed Re

                    "RO" ->
                        Decode.succeed Ro

                    "RU" ->
                        Decode.succeed Ru

                    "RW" ->
                        Decode.succeed Rw

                    "BL" ->
                        Decode.succeed Bl

                    "SH" ->
                        Decode.succeed Sh

                    "KN" ->
                        Decode.succeed Kn

                    "LC" ->
                        Decode.succeed Lc

                    "MF" ->
                        Decode.succeed Mf

                    "PM" ->
                        Decode.succeed Pm

                    "WS" ->
                        Decode.succeed Ws

                    "SM" ->
                        Decode.succeed Sm

                    "ST" ->
                        Decode.succeed St

                    "SA" ->
                        Decode.succeed Sa

                    "SN" ->
                        Decode.succeed Sn

                    "RS" ->
                        Decode.succeed Rs

                    "SC" ->
                        Decode.succeed Sc

                    "SL" ->
                        Decode.succeed Sl

                    "SG" ->
                        Decode.succeed Sg

                    "SX" ->
                        Decode.succeed Sx

                    "SK" ->
                        Decode.succeed Sk

                    "SI" ->
                        Decode.succeed Si

                    "SB" ->
                        Decode.succeed Sb

                    "SO" ->
                        Decode.succeed So

                    "ZA" ->
                        Decode.succeed Za

                    "GS" ->
                        Decode.succeed Gs

                    "KR" ->
                        Decode.succeed Kr

                    "SS" ->
                        Decode.succeed Ss

                    "ES" ->
                        Decode.succeed Es

                    "LK" ->
                        Decode.succeed Lk

                    "VC" ->
                        Decode.succeed Vc

                    "SD" ->
                        Decode.succeed Sd

                    "SR" ->
                        Decode.succeed Sr

                    "SJ" ->
                        Decode.succeed Sj

                    "SE" ->
                        Decode.succeed Se

                    "CH" ->
                        Decode.succeed Ch

                    "SY" ->
                        Decode.succeed Sy

                    "TW" ->
                        Decode.succeed Tw

                    "TJ" ->
                        Decode.succeed Tj

                    "TZ" ->
                        Decode.succeed Tz

                    "TH" ->
                        Decode.succeed Th

                    "TL" ->
                        Decode.succeed Tl

                    "TG" ->
                        Decode.succeed Tg

                    "TK" ->
                        Decode.succeed Tk

                    "TO" ->
                        Decode.succeed To

                    "TT" ->
                        Decode.succeed Tt

                    "TA" ->
                        Decode.succeed Ta

                    "TN" ->
                        Decode.succeed Tn

                    "TR" ->
                        Decode.succeed Tr

                    "TM" ->
                        Decode.succeed Tm

                    "TC" ->
                        Decode.succeed Tc

                    "TV" ->
                        Decode.succeed Tv

                    "UG" ->
                        Decode.succeed Ug

                    "UA" ->
                        Decode.succeed Ua

                    "AE" ->
                        Decode.succeed Ae

                    "GB" ->
                        Decode.succeed Gb

                    "US" ->
                        Decode.succeed Us

                    "UM" ->
                        Decode.succeed Um

                    "UY" ->
                        Decode.succeed Uy

                    "UZ" ->
                        Decode.succeed Uz

                    "VU" ->
                        Decode.succeed Vu

                    "VE" ->
                        Decode.succeed Ve

                    "VN" ->
                        Decode.succeed Vn

                    "VG" ->
                        Decode.succeed Vg

                    "WF" ->
                        Decode.succeed Wf

                    "EH" ->
                        Decode.succeed Eh

                    "YE" ->
                        Decode.succeed Ye

                    "ZM" ->
                        Decode.succeed Zm

                    "ZW" ->
                        Decode.succeed Zw

                    "ZZ" ->
                        Decode.succeed Zz

                    _ ->
                        Decode.fail ("Invalid CountryCode type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CountryCode -> String
toString enum____ =
    case enum____ of
        Af ->
            "AF"

        Ax ->
            "AX"

        Al ->
            "AL"

        Dz ->
            "DZ"

        Ad ->
            "AD"

        Ao ->
            "AO"

        Ai ->
            "AI"

        Ag ->
            "AG"

        Ar ->
            "AR"

        Am ->
            "AM"

        Aw ->
            "AW"

        Ac ->
            "AC"

        Au ->
            "AU"

        At ->
            "AT"

        Az ->
            "AZ"

        Bs ->
            "BS"

        Bh ->
            "BH"

        Bd ->
            "BD"

        Bb ->
            "BB"

        By ->
            "BY"

        Be ->
            "BE"

        Bz ->
            "BZ"

        Bj ->
            "BJ"

        Bm ->
            "BM"

        Bt ->
            "BT"

        Bo ->
            "BO"

        Ba ->
            "BA"

        Bw ->
            "BW"

        Bv ->
            "BV"

        Br ->
            "BR"

        Io ->
            "IO"

        Bn ->
            "BN"

        Bg ->
            "BG"

        Bf ->
            "BF"

        Bi ->
            "BI"

        Kh ->
            "KH"

        Ca ->
            "CA"

        Cv ->
            "CV"

        Bq ->
            "BQ"

        Ky ->
            "KY"

        Cf ->
            "CF"

        Td ->
            "TD"

        Cl ->
            "CL"

        Cn ->
            "CN"

        Cx ->
            "CX"

        Cc ->
            "CC"

        Co ->
            "CO"

        Km ->
            "KM"

        Cg ->
            "CG"

        Cd ->
            "CD"

        Ck ->
            "CK"

        Cr ->
            "CR"

        Hr ->
            "HR"

        Cu ->
            "CU"

        Cw ->
            "CW"

        Cy ->
            "CY"

        Cz ->
            "CZ"

        Ci ->
            "CI"

        Dk ->
            "DK"

        Dj ->
            "DJ"

        Dm ->
            "DM"

        Do ->
            "DO"

        Ec ->
            "EC"

        Eg ->
            "EG"

        Sv ->
            "SV"

        Gq ->
            "GQ"

        Er ->
            "ER"

        Ee ->
            "EE"

        Sz ->
            "SZ"

        Et ->
            "ET"

        Fk ->
            "FK"

        Fo ->
            "FO"

        Fj ->
            "FJ"

        Fi ->
            "FI"

        Fr ->
            "FR"

        Gf ->
            "GF"

        Pf ->
            "PF"

        Tf ->
            "TF"

        Ga ->
            "GA"

        Gm ->
            "GM"

        Ge ->
            "GE"

        De ->
            "DE"

        Gh ->
            "GH"

        Gi ->
            "GI"

        Gr ->
            "GR"

        Gl ->
            "GL"

        Gd ->
            "GD"

        Gp ->
            "GP"

        Gt ->
            "GT"

        Gg ->
            "GG"

        Gn ->
            "GN"

        Gw ->
            "GW"

        Gy ->
            "GY"

        Ht ->
            "HT"

        Hm ->
            "HM"

        Va ->
            "VA"

        Hn ->
            "HN"

        Hk ->
            "HK"

        Hu ->
            "HU"

        Is ->
            "IS"

        In ->
            "IN"

        Id ->
            "ID"

        Ir ->
            "IR"

        Iq ->
            "IQ"

        Ie ->
            "IE"

        Im ->
            "IM"

        Il ->
            "IL"

        It ->
            "IT"

        Jm ->
            "JM"

        Jp ->
            "JP"

        Je ->
            "JE"

        Jo ->
            "JO"

        Kz ->
            "KZ"

        Ke ->
            "KE"

        Ki ->
            "KI"

        Kp ->
            "KP"

        Xk ->
            "XK"

        Kw ->
            "KW"

        Kg ->
            "KG"

        La ->
            "LA"

        Lv ->
            "LV"

        Lb ->
            "LB"

        Ls ->
            "LS"

        Lr ->
            "LR"

        Ly ->
            "LY"

        Li ->
            "LI"

        Lt ->
            "LT"

        Lu ->
            "LU"

        Mo ->
            "MO"

        Mg ->
            "MG"

        Mw ->
            "MW"

        My ->
            "MY"

        Mv ->
            "MV"

        Ml ->
            "ML"

        Mt ->
            "MT"

        Mq ->
            "MQ"

        Mr ->
            "MR"

        Mu ->
            "MU"

        Yt ->
            "YT"

        Mx ->
            "MX"

        Md ->
            "MD"

        Mc ->
            "MC"

        Mn ->
            "MN"

        Me ->
            "ME"

        Ms ->
            "MS"

        Ma ->
            "MA"

        Mz ->
            "MZ"

        Mm ->
            "MM"

        Na ->
            "NA"

        Nr ->
            "NR"

        Np ->
            "NP"

        Nl ->
            "NL"

        An ->
            "AN"

        Nc ->
            "NC"

        Nz ->
            "NZ"

        Ni ->
            "NI"

        Ne ->
            "NE"

        Ng ->
            "NG"

        Nu ->
            "NU"

        Nf ->
            "NF"

        Mk ->
            "MK"

        No ->
            "NO"

        Om ->
            "OM"

        Pk ->
            "PK"

        Ps ->
            "PS"

        Pa ->
            "PA"

        Pg ->
            "PG"

        Py ->
            "PY"

        Pe ->
            "PE"

        Ph ->
            "PH"

        Pn ->
            "PN"

        Pl ->
            "PL"

        Pt ->
            "PT"

        Qa ->
            "QA"

        Cm ->
            "CM"

        Re ->
            "RE"

        Ro ->
            "RO"

        Ru ->
            "RU"

        Rw ->
            "RW"

        Bl ->
            "BL"

        Sh ->
            "SH"

        Kn ->
            "KN"

        Lc ->
            "LC"

        Mf ->
            "MF"

        Pm ->
            "PM"

        Ws ->
            "WS"

        Sm ->
            "SM"

        St ->
            "ST"

        Sa ->
            "SA"

        Sn ->
            "SN"

        Rs ->
            "RS"

        Sc ->
            "SC"

        Sl ->
            "SL"

        Sg ->
            "SG"

        Sx ->
            "SX"

        Sk ->
            "SK"

        Si ->
            "SI"

        Sb ->
            "SB"

        So ->
            "SO"

        Za ->
            "ZA"

        Gs ->
            "GS"

        Kr ->
            "KR"

        Ss ->
            "SS"

        Es ->
            "ES"

        Lk ->
            "LK"

        Vc ->
            "VC"

        Sd ->
            "SD"

        Sr ->
            "SR"

        Sj ->
            "SJ"

        Se ->
            "SE"

        Ch ->
            "CH"

        Sy ->
            "SY"

        Tw ->
            "TW"

        Tj ->
            "TJ"

        Tz ->
            "TZ"

        Th ->
            "TH"

        Tl ->
            "TL"

        Tg ->
            "TG"

        Tk ->
            "TK"

        To ->
            "TO"

        Tt ->
            "TT"

        Ta ->
            "TA"

        Tn ->
            "TN"

        Tr ->
            "TR"

        Tm ->
            "TM"

        Tc ->
            "TC"

        Tv ->
            "TV"

        Ug ->
            "UG"

        Ua ->
            "UA"

        Ae ->
            "AE"

        Gb ->
            "GB"

        Us ->
            "US"

        Um ->
            "UM"

        Uy ->
            "UY"

        Uz ->
            "UZ"

        Vu ->
            "VU"

        Ve ->
            "VE"

        Vn ->
            "VN"

        Vg ->
            "VG"

        Wf ->
            "WF"

        Eh ->
            "EH"

        Ye ->
            "YE"

        Zm ->
            "ZM"

        Zw ->
            "ZW"

        Zz ->
            "ZZ"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CountryCode
fromString enumString____ =
    case enumString____ of
        "AF" ->
            Just Af

        "AX" ->
            Just Ax

        "AL" ->
            Just Al

        "DZ" ->
            Just Dz

        "AD" ->
            Just Ad

        "AO" ->
            Just Ao

        "AI" ->
            Just Ai

        "AG" ->
            Just Ag

        "AR" ->
            Just Ar

        "AM" ->
            Just Am

        "AW" ->
            Just Aw

        "AC" ->
            Just Ac

        "AU" ->
            Just Au

        "AT" ->
            Just At

        "AZ" ->
            Just Az

        "BS" ->
            Just Bs

        "BH" ->
            Just Bh

        "BD" ->
            Just Bd

        "BB" ->
            Just Bb

        "BY" ->
            Just By

        "BE" ->
            Just Be

        "BZ" ->
            Just Bz

        "BJ" ->
            Just Bj

        "BM" ->
            Just Bm

        "BT" ->
            Just Bt

        "BO" ->
            Just Bo

        "BA" ->
            Just Ba

        "BW" ->
            Just Bw

        "BV" ->
            Just Bv

        "BR" ->
            Just Br

        "IO" ->
            Just Io

        "BN" ->
            Just Bn

        "BG" ->
            Just Bg

        "BF" ->
            Just Bf

        "BI" ->
            Just Bi

        "KH" ->
            Just Kh

        "CA" ->
            Just Ca

        "CV" ->
            Just Cv

        "BQ" ->
            Just Bq

        "KY" ->
            Just Ky

        "CF" ->
            Just Cf

        "TD" ->
            Just Td

        "CL" ->
            Just Cl

        "CN" ->
            Just Cn

        "CX" ->
            Just Cx

        "CC" ->
            Just Cc

        "CO" ->
            Just Co

        "KM" ->
            Just Km

        "CG" ->
            Just Cg

        "CD" ->
            Just Cd

        "CK" ->
            Just Ck

        "CR" ->
            Just Cr

        "HR" ->
            Just Hr

        "CU" ->
            Just Cu

        "CW" ->
            Just Cw

        "CY" ->
            Just Cy

        "CZ" ->
            Just Cz

        "CI" ->
            Just Ci

        "DK" ->
            Just Dk

        "DJ" ->
            Just Dj

        "DM" ->
            Just Dm

        "DO" ->
            Just Do

        "EC" ->
            Just Ec

        "EG" ->
            Just Eg

        "SV" ->
            Just Sv

        "GQ" ->
            Just Gq

        "ER" ->
            Just Er

        "EE" ->
            Just Ee

        "SZ" ->
            Just Sz

        "ET" ->
            Just Et

        "FK" ->
            Just Fk

        "FO" ->
            Just Fo

        "FJ" ->
            Just Fj

        "FI" ->
            Just Fi

        "FR" ->
            Just Fr

        "GF" ->
            Just Gf

        "PF" ->
            Just Pf

        "TF" ->
            Just Tf

        "GA" ->
            Just Ga

        "GM" ->
            Just Gm

        "GE" ->
            Just Ge

        "DE" ->
            Just De

        "GH" ->
            Just Gh

        "GI" ->
            Just Gi

        "GR" ->
            Just Gr

        "GL" ->
            Just Gl

        "GD" ->
            Just Gd

        "GP" ->
            Just Gp

        "GT" ->
            Just Gt

        "GG" ->
            Just Gg

        "GN" ->
            Just Gn

        "GW" ->
            Just Gw

        "GY" ->
            Just Gy

        "HT" ->
            Just Ht

        "HM" ->
            Just Hm

        "VA" ->
            Just Va

        "HN" ->
            Just Hn

        "HK" ->
            Just Hk

        "HU" ->
            Just Hu

        "IS" ->
            Just Is

        "IN" ->
            Just In

        "ID" ->
            Just Id

        "IR" ->
            Just Ir

        "IQ" ->
            Just Iq

        "IE" ->
            Just Ie

        "IM" ->
            Just Im

        "IL" ->
            Just Il

        "IT" ->
            Just It

        "JM" ->
            Just Jm

        "JP" ->
            Just Jp

        "JE" ->
            Just Je

        "JO" ->
            Just Jo

        "KZ" ->
            Just Kz

        "KE" ->
            Just Ke

        "KI" ->
            Just Ki

        "KP" ->
            Just Kp

        "XK" ->
            Just Xk

        "KW" ->
            Just Kw

        "KG" ->
            Just Kg

        "LA" ->
            Just La

        "LV" ->
            Just Lv

        "LB" ->
            Just Lb

        "LS" ->
            Just Ls

        "LR" ->
            Just Lr

        "LY" ->
            Just Ly

        "LI" ->
            Just Li

        "LT" ->
            Just Lt

        "LU" ->
            Just Lu

        "MO" ->
            Just Mo

        "MG" ->
            Just Mg

        "MW" ->
            Just Mw

        "MY" ->
            Just My

        "MV" ->
            Just Mv

        "ML" ->
            Just Ml

        "MT" ->
            Just Mt

        "MQ" ->
            Just Mq

        "MR" ->
            Just Mr

        "MU" ->
            Just Mu

        "YT" ->
            Just Yt

        "MX" ->
            Just Mx

        "MD" ->
            Just Md

        "MC" ->
            Just Mc

        "MN" ->
            Just Mn

        "ME" ->
            Just Me

        "MS" ->
            Just Ms

        "MA" ->
            Just Ma

        "MZ" ->
            Just Mz

        "MM" ->
            Just Mm

        "NA" ->
            Just Na

        "NR" ->
            Just Nr

        "NP" ->
            Just Np

        "NL" ->
            Just Nl

        "AN" ->
            Just An

        "NC" ->
            Just Nc

        "NZ" ->
            Just Nz

        "NI" ->
            Just Ni

        "NE" ->
            Just Ne

        "NG" ->
            Just Ng

        "NU" ->
            Just Nu

        "NF" ->
            Just Nf

        "MK" ->
            Just Mk

        "NO" ->
            Just No

        "OM" ->
            Just Om

        "PK" ->
            Just Pk

        "PS" ->
            Just Ps

        "PA" ->
            Just Pa

        "PG" ->
            Just Pg

        "PY" ->
            Just Py

        "PE" ->
            Just Pe

        "PH" ->
            Just Ph

        "PN" ->
            Just Pn

        "PL" ->
            Just Pl

        "PT" ->
            Just Pt

        "QA" ->
            Just Qa

        "CM" ->
            Just Cm

        "RE" ->
            Just Re

        "RO" ->
            Just Ro

        "RU" ->
            Just Ru

        "RW" ->
            Just Rw

        "BL" ->
            Just Bl

        "SH" ->
            Just Sh

        "KN" ->
            Just Kn

        "LC" ->
            Just Lc

        "MF" ->
            Just Mf

        "PM" ->
            Just Pm

        "WS" ->
            Just Ws

        "SM" ->
            Just Sm

        "ST" ->
            Just St

        "SA" ->
            Just Sa

        "SN" ->
            Just Sn

        "RS" ->
            Just Rs

        "SC" ->
            Just Sc

        "SL" ->
            Just Sl

        "SG" ->
            Just Sg

        "SX" ->
            Just Sx

        "SK" ->
            Just Sk

        "SI" ->
            Just Si

        "SB" ->
            Just Sb

        "SO" ->
            Just So

        "ZA" ->
            Just Za

        "GS" ->
            Just Gs

        "KR" ->
            Just Kr

        "SS" ->
            Just Ss

        "ES" ->
            Just Es

        "LK" ->
            Just Lk

        "VC" ->
            Just Vc

        "SD" ->
            Just Sd

        "SR" ->
            Just Sr

        "SJ" ->
            Just Sj

        "SE" ->
            Just Se

        "CH" ->
            Just Ch

        "SY" ->
            Just Sy

        "TW" ->
            Just Tw

        "TJ" ->
            Just Tj

        "TZ" ->
            Just Tz

        "TH" ->
            Just Th

        "TL" ->
            Just Tl

        "TG" ->
            Just Tg

        "TK" ->
            Just Tk

        "TO" ->
            Just To

        "TT" ->
            Just Tt

        "TA" ->
            Just Ta

        "TN" ->
            Just Tn

        "TR" ->
            Just Tr

        "TM" ->
            Just Tm

        "TC" ->
            Just Tc

        "TV" ->
            Just Tv

        "UG" ->
            Just Ug

        "UA" ->
            Just Ua

        "AE" ->
            Just Ae

        "GB" ->
            Just Gb

        "US" ->
            Just Us

        "UM" ->
            Just Um

        "UY" ->
            Just Uy

        "UZ" ->
            Just Uz

        "VU" ->
            Just Vu

        "VE" ->
            Just Ve

        "VN" ->
            Just Vn

        "VG" ->
            Just Vg

        "WF" ->
            Just Wf

        "EH" ->
            Just Eh

        "YE" ->
            Just Ye

        "ZM" ->
            Just Zm

        "ZW" ->
            Just Zw

        "ZZ" ->
            Just Zz

        _ ->
            Nothing
