-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.FilterType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The type of data that the filter group represents.

For more information, refer to [Filter products in a collection with the Storefront API]
(<https://shopify.dev/api/examples/filter-products>).

  - List - A list of selectable values.
  - PriceRange - A range of prices.
  - Boolean - A boolean value.

-}
type FilterType
    = List
    | PriceRange
    | Boolean


list : List FilterType
list =
    [ List, PriceRange, Boolean ]


decoder : Decoder FilterType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "LIST" ->
                        Decode.succeed List

                    "PRICE_RANGE" ->
                        Decode.succeed PriceRange

                    "BOOLEAN" ->
                        Decode.succeed Boolean

                    _ ->
                        Decode.fail ("Invalid FilterType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : FilterType -> String
toString enum____ =
    case enum____ of
        List ->
            "LIST"

        PriceRange ->
            "PRICE_RANGE"

        Boolean ->
            "BOOLEAN"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe FilterType
fromString enumString____ =
    case enumString____ of
        "LIST" ->
            Just List

        "PRICE_RANGE" ->
            Just PriceRange

        "BOOLEAN" ->
            Just Boolean

        _ ->
            Nothing
