-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.OrderSortKeys exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The set of valid sort keys for the Order query.

  - ProcessedAt - Sort by the `processed_at` value.
  - TotalPrice - Sort by the `total_price` value.
  - Id - Sort by the `id` value.
  - Relevance - Sort by relevance to the search terms when the `query` parameter is specified on the connection.
    Don't use this sort key when no search query is specified.

-}
type OrderSortKeys
    = ProcessedAt
    | TotalPrice
    | Id
    | Relevance


list : List OrderSortKeys
list =
    [ ProcessedAt, TotalPrice, Id, Relevance ]


decoder : Decoder OrderSortKeys
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PROCESSED_AT" ->
                        Decode.succeed ProcessedAt

                    "TOTAL_PRICE" ->
                        Decode.succeed TotalPrice

                    "ID" ->
                        Decode.succeed Id

                    "RELEVANCE" ->
                        Decode.succeed Relevance

                    _ ->
                        Decode.fail ("Invalid OrderSortKeys type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : OrderSortKeys -> String
toString enum____ =
    case enum____ of
        ProcessedAt ->
            "PROCESSED_AT"

        TotalPrice ->
            "TOTAL_PRICE"

        Id ->
            "ID"

        Relevance ->
            "RELEVANCE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe OrderSortKeys
fromString enumString____ =
    case enumString____ of
        "PROCESSED_AT" ->
            Just ProcessedAt

        "TOTAL_PRICE" ->
            Just TotalPrice

        "ID" ->
            Just Id

        "RELEVANCE" ->
            Just Relevance

        _ ->
            Nothing
