-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.ProductVariantSortKeys exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The set of valid sort keys for the ProductVariant query.

  - Title - Sort by the `title` value.
  - Sku - Sort by the `sku` value.
  - Position - Sort by the `position` value.
  - Id - Sort by the `id` value.
  - Relevance - Sort by relevance to the search terms when the `query` parameter is specified on the connection.
    Don't use this sort key when no search query is specified.

-}
type ProductVariantSortKeys
    = Title
    | Sku
    | Position
    | Id
    | Relevance


list : List ProductVariantSortKeys
list =
    [ Title, Sku, Position, Id, Relevance ]


decoder : Decoder ProductVariantSortKeys
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "TITLE" ->
                        Decode.succeed Title

                    "SKU" ->
                        Decode.succeed Sku

                    "POSITION" ->
                        Decode.succeed Position

                    "ID" ->
                        Decode.succeed Id

                    "RELEVANCE" ->
                        Decode.succeed Relevance

                    _ ->
                        Decode.fail ("Invalid ProductVariantSortKeys type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ProductVariantSortKeys -> String
toString enum____ =
    case enum____ of
        Title ->
            "TITLE"

        Sku ->
            "SKU"

        Position ->
            "POSITION"

        Id ->
            "ID"

        Relevance ->
            "RELEVANCE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ProductVariantSortKeys
fromString enumString____ =
    case enumString____ of
        "TITLE" ->
            Just Title

        "SKU" ->
            Just Sku

        "POSITION" ->
            Just Position

        "ID" ->
            Just Id

        "RELEVANCE" ->
            Just Relevance

        _ ->
            Nothing
