-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.TransactionStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Transaction statuses describe the status of a transaction.

  - Pending - The transaction is pending.
  - Success - The transaction succeeded.
  - Failure - The transaction failed.
  - Error - There was an error while processing the transaction.

-}
type TransactionStatus
    = Pending
    | Success
    | Failure
    | Error


list : List TransactionStatus
list =
    [ Pending, Success, Failure, Error ]


decoder : Decoder TransactionStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PENDING" ->
                        Decode.succeed Pending

                    "SUCCESS" ->
                        Decode.succeed Success

                    "FAILURE" ->
                        Decode.succeed Failure

                    "ERROR" ->
                        Decode.succeed Error

                    _ ->
                        Decode.fail ("Invalid TransactionStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TransactionStatus -> String
toString enum____ =
    case enum____ of
        Pending ->
            "PENDING"

        Success ->
            "SUCCESS"

        Failure ->
            "FAILURE"

        Error ->
            "ERROR"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TransactionStatus
fromString enumString____ =
    case enumString____ of
        "PENDING" ->
            Just Pending

        "SUCCESS" ->
            Just Success

        "FAILURE" ->
            Just Failure

        "ERROR" ->
            Just Error

        _ ->
            Nothing
