-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Enum.WeightUnit exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Units of measurement for weight.

  - Kilograms - 1 kilogram equals 1000 grams.
  - Grams - Metric system unit of mass.
  - Pounds - 1 pound equals 16 ounces.
  - Ounces - Imperial system unit of mass.

-}
type WeightUnit
    = Kilograms
    | Grams
    | Pounds
    | Ounces


list : List WeightUnit
list =
    [ Kilograms, Grams, Pounds, Ounces ]


decoder : Decoder WeightUnit
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "KILOGRAMS" ->
                        Decode.succeed Kilograms

                    "GRAMS" ->
                        Decode.succeed Grams

                    "POUNDS" ->
                        Decode.succeed Pounds

                    "OUNCES" ->
                        Decode.succeed Ounces

                    _ ->
                        Decode.fail ("Invalid WeightUnit type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : WeightUnit -> String
toString enum____ =
    case enum____ of
        Kilograms ->
            "KILOGRAMS"

        Grams ->
            "GRAMS"

        Pounds ->
            "POUNDS"

        Ounces ->
            "OUNCES"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe WeightUnit
fromString enumString____ =
    case enumString____ of
        "KILOGRAMS" ->
            Just Kilograms

        "GRAMS" ->
            Just Grams

        "POUNDS" ->
            Just Pounds

        "OUNCES" ->
            Just Ounces

        _ ->
            Nothing
