-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Interface.CartDiscountAllocation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


type alias Fragments decodesTo =
    { onCartAutomaticDiscountAllocation : SelectionSet decodesTo Shopify.Object.CartAutomaticDiscountAllocation
    , onCartCodeDiscountAllocation : SelectionSet decodesTo Shopify.Object.CartCodeDiscountAllocation
    , onCartCustomDiscountAllocation : SelectionSet decodesTo Shopify.Object.CartCustomDiscountAllocation
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Shopify.Interface.CartDiscountAllocation
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "CartAutomaticDiscountAllocation" selections____.onCartAutomaticDiscountAllocation
        , Object.buildFragment "CartCodeDiscountAllocation" selections____.onCartCodeDiscountAllocation
        , Object.buildFragment "CartCustomDiscountAllocation" selections____.onCartCustomDiscountAllocation
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onCartAutomaticDiscountAllocation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCartCodeDiscountAllocation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCartCustomDiscountAllocation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The discounted amount that has been applied to the cart line.
-}
discountedAmount :
    SelectionSet decodesTo Shopify.Object.MoneyV2
    -> SelectionSet decodesTo Shopify.Interface.CartDiscountAllocation
discountedAmount object____ =
    Object.selectionForCompositeField "discountedAmount" [] object____ Basics.identity
