-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Interface.DiscountApplication exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode
import Shopify.Enum.DiscountApplicationAllocationMethod
import Shopify.Enum.DiscountApplicationTargetSelection
import Shopify.Enum.DiscountApplicationTargetType
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


type alias Fragments decodesTo =
    { onAutomaticDiscountApplication : SelectionSet decodesTo Shopify.Object.AutomaticDiscountApplication
    , onDiscountCodeApplication : SelectionSet decodesTo Shopify.Object.DiscountCodeApplication
    , onManualDiscountApplication : SelectionSet decodesTo Shopify.Object.ManualDiscountApplication
    , onScriptDiscountApplication : SelectionSet decodesTo Shopify.Object.ScriptDiscountApplication
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Shopify.Interface.DiscountApplication
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "AutomaticDiscountApplication" selections____.onAutomaticDiscountApplication
        , Object.buildFragment "DiscountCodeApplication" selections____.onDiscountCodeApplication
        , Object.buildFragment "ManualDiscountApplication" selections____.onManualDiscountApplication
        , Object.buildFragment "ScriptDiscountApplication" selections____.onScriptDiscountApplication
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onAutomaticDiscountApplication = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDiscountCodeApplication = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onManualDiscountApplication = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onScriptDiscountApplication = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The method by which the discount's value is allocated to its entitled items.
-}
allocationMethod : SelectionSet Shopify.Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod Shopify.Interface.DiscountApplication
allocationMethod =
    Object.selectionForField "Enum.DiscountApplicationAllocationMethod.DiscountApplicationAllocationMethod" "allocationMethod" [] Shopify.Enum.DiscountApplicationAllocationMethod.decoder


{-| Which lines of targetType that the discount is allocated over.
-}
targetSelection : SelectionSet Shopify.Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection Shopify.Interface.DiscountApplication
targetSelection =
    Object.selectionForField "Enum.DiscountApplicationTargetSelection.DiscountApplicationTargetSelection" "targetSelection" [] Shopify.Enum.DiscountApplicationTargetSelection.decoder


{-| The type of line that the discount is applicable towards.
-}
targetType : SelectionSet Shopify.Enum.DiscountApplicationTargetType.DiscountApplicationTargetType Shopify.Interface.DiscountApplication
targetType =
    Object.selectionForField "Enum.DiscountApplicationTargetType.DiscountApplicationTargetType" "targetType" [] Shopify.Enum.DiscountApplicationTargetType.decoder


{-| The value of the discount application.
-}
value :
    SelectionSet decodesTo Shopify.Union.PricingValue
    -> SelectionSet decodesTo Shopify.Interface.DiscountApplication
value object____ =
    Object.selectionForCompositeField "value" [] object____ Basics.identity
