-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shopify.Interface.DisplayableError exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode
import Shopify.InputObject
import Shopify.Interface
import Shopify.Object
import Shopify.Scalar
import Shopify.ScalarCodecs
import Shopify.Union


type alias Fragments decodesTo =
    { onCartUserError : SelectionSet decodesTo Shopify.Object.CartUserError
    , onCheckoutUserError : SelectionSet decodesTo Shopify.Object.CheckoutUserError
    , onCustomerUserError : SelectionSet decodesTo Shopify.Object.CustomerUserError
    , onUserError : SelectionSet decodesTo Shopify.Object.UserError
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Shopify.Interface.DisplayableError
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "CartUserError" selections____.onCartUserError
        , Object.buildFragment "CheckoutUserError" selections____.onCheckoutUserError
        , Object.buildFragment "CustomerUserError" selections____.onCustomerUserError
        , Object.buildFragment "UserError" selections____.onUserError
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onCartUserError = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCheckoutUserError = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCustomerUserError = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUserError = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The path to the input field that caused the error.
-}
field : SelectionSet (Maybe (List String)) Shopify.Interface.DisplayableError
field =
    Object.selectionForField "(Maybe (List String))" "field" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The error message.
-}
message : SelectionSet String Shopify.Interface.DisplayableError
message =
    Object.selectionForField "String" "message" [] Decode.string
